version: '3.8'
services:
  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=aziz
      - DATABASE_NAME=itex_db
      - DATABASE_SYNCHRONIZE=true
      - DATABASE_MIGRATIONS_RUN=true

  db:
    container_name: itex_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=aziz
      - MYSQL_DATABASE=itex_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
